{
 "title": "Akkoma Dashboard",
 "description": "halp",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Failed AP deliveries",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(akkoma_ap_delivery_fail_final{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__interval]) != 0",
     "legendFormat": "{{target}} - {{reason}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(up{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[5m])\n# or if you want to count downtime of the Prometheus scraper as Akkoma downtime too,\n# e.g. because both services are on the same host, you can use the following with VictoriaMetrics:\n   #avg_over_time((up{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"} default 0.0)[5m])\n# or this more complex query for plain Prometheus:\n#   avg_over_time(sum(up{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"} or 0.0)[5m])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "raw", "reducer": "mean", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" }
   ]
  },
  {
   "title": "Local Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "pleroma_local_users_total{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "pleroma_local_statuses_total{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}",
     "legendFormat": "Posts"
    }
   ]
  },
  {
   "title": "Remote Resrc. Estimates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "pleroma_remote_users_total{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "pleroma_domains_total{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}",
     "legendFormat": "Domains"
    }
   ]
  },
  {
   "title": "BEAM System Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "${memsum} / ${memcnt}", "type": "math" },
    { "expression": "${cpusum} / ${cpucnt}", "type": "math" },
    { "expression": "${iosum} / ${iocnt}", "type": "math" }
   ]
  },
  {
   "title": "Receive, Fetch, Publish Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(oban_job_completion_count{worker=~\"Pleroma.Workers.RemoteFetcherWorker|Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker\", instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__interval])",
     "legendFormat": "Completions: {{worker}}"
    },
    {
     "expr": "increase(oban_job_exception_count{worker=~\"Pleroma.Workers.RemoteFetcherWorker|Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker\", instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__interval])",
     "legendFormat": "Exceptions: {{worker}}"
    }
   ]
  },
  {
   "title": "Single DB Query (95% quantiles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(pleroma_repo_query_queue_time_bucket{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval]))",
     "legendFormat": "Queue"
    },
    {
     "expr": "histogram_quantile(0.95, rate(pleroma_repo_query_decode_time_fdist_bucket{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval]))",
     "legendFormat": "Decode"
    },
    {
     "expr": "histogram_quantile(0.95, rate(pleroma_repo_query_query_time_fdist_bucket{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval]))",
     "legendFormat": "Query"
    },
    { "expression": "${totalsum} / ${totalcnt}", "type": "math" }
   ]
  },
  {
   "title": "Total DB Query Times per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pleroma_repo_query_queue_time_sum{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval])",
     "legendFormat": "Queue"
    },
    {
     "expr": "rate(pleroma_repo_query_decode_time_fdist_sum{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval])",
     "legendFormat": "Decode"
    },
    {
     "expr": "rate(pleroma_repo_query_query_time_fdist_sum{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval])",
     "legendFormat": "Query"
    },
    {
     "expr": "rate(pleroma_repo_query_total_time_sum{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(tesla_request_completed_count{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__interval])",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Job Completions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(oban_job_completion_count{worker!~\"Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker|Pleroma.Workers.RemoteFetcherWorker\", instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__interval])",
     "legendFormat": "Completion: {{worker}}"
    }
   ]
  },
  {
   "title": "Job Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(oban_job_exception_count{worker!~\"Pleroma.Workers.ReceiverWorker|Pleroma.Workers.RemoteFetcherWorker|Pleroma.Workers.PublisherWorker\", instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__interval])",
     "legendFormat": "Exception: {{worker}}"
    }
   ]
  },
  {
   "title": "Total Job Proc. Time per Second",
   "type": "timeseries",
   "description": "Times are counted upon job completion/failure and may contain IO or network wait times.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oban_job_completion_sum{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval])",
     "legendFormat": "{{worker}} (c)"
    },
    {
     "expr": "rate(oban_job_exception_sum{instance=\"${INSTANCE}\", job=\"${SCRAPE_JOB}\"}[$__rate_interval])",
     "legendFormat": "{{worker}} (e)"
    }
   ]
  },
  {
   "title": "Inbound HTTP Proc. Time per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(phoenix_router_dispatch_stop_duration_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    },
    {
     "expr": "sum(rate(phoenix_router_dispatch_stop_duration_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "timeseries",
   "description": "Jobs eligible for immediate execution, but not yet started. Most likely they’re held back because the queue is already saturated and there’s no free slot.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "akkoma_job_queue_available", "legendFormat": "{{queue_name}}" }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "timeseries",
   "description": "Jobs intentionally held back until a later start date. This also (but not only) includes retries of previously failed jobs since there’s a cooldown between re-attempts.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "akkoma_job_queue_scheduled", "legendFormat": "{{queue_name}}" }
   ]
  },
  {
   "title": "Inbound Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(phoenix_router_dispatch_stop_duration_count{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "BEAM VM Memory Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "${memsum} / ${memcnt}", "type": "math" }
   ]
  },
  {
   "title": "VM Port IO Traffic",
   "type": "timeseries",
   "description": "Includes network traffic, but also communication to local non-elixir components like fast_html workers",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(vm_portio_in_total{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__interval])",
     "legendFormat": "in"
    },
    {
     "expr": "increase(vm_portio_out_total{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Jobs Per Minute - 24h Average",
   "type": "timeseries",
   "description": "For improved insight this is tracks  federation-related jobs, i.e. RFP (Receive, Fetch, Publish) jobs, separately from everything else",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time((rate(sum(oban_job_completion_count{worker!~\"Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker|Pleroma.Workers.RemoteFetcherWorker\", job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"})[1m]) or 0)[24h]) * 60",
     "legendFormat": "Completions"
    },
    {
     "expr": "avg_over_time((rate(sum(oban_job_exception_count{worker!~\"Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker|Pleroma.Workers.RemoteFetcherWorker\", job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"})[1m]) or 0)[24h]) * 60",
     "legendFormat": "Exceptions"
    },
    {
     "expr": "avg_over_time((rate(sum(oban_job_completion_count{worker=~\"Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker|Pleroma.Workers.RemoteFetcherWorker\", job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"})[1m]) or 0)[24h]) * 60 ",
     "legendFormat": "RFP Completions"
    },
    {
     "expr": "avg_over_time((rate(sum(oban_job_exception_count{worker=~\"Pleroma.Workers.ReceiverWorker|Pleroma.Workers.PublisherWorker|Pleroma.Workers.RemoteFetcherWorker\", job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"})[1m]) or 0)[24h]) * 60 ",
     "legendFormat": "RFP Exceptions"
    }
   ]
  },
  {
   "title": "Inbound Requests per Min. - 24h Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(phoenix_router_dispatch_stop_duration_count{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval]))[24h]) * 60",
     "legendFormat": "Inbound Requests per Minute"
    }
   ]
  },
  {
   "title": "DB and Job Time Per Min - 48h Avg",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(rate(pleroma_repo_query_query_time_fdist_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval])[48h]) * 60\n# By default downtime is excluded from average; use below if it should count as zeroes instead (only on VictoriaMetrics)\n# avg_over_time(rate(pleroma_repo_query_query_time_fdist_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval] default 0)[48h]) * 60",
     "legendFormat": "DB Query"
    },
    {
     "expr": "avg_over_time(rate(pleroma_repo_query_total_time_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval])[48h]) * 60\n# By default downtime is excluded from average; use below if it should count as zeroes instead (only on VictoriaMetrics):\n# avg_over_time(rate(pleroma_repo_query_total_time_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval] default 0)[48h]) * 60",
     "legendFormat": "DB Total"
    },
    {
     "expr": "avg_over_time((rate((sum(oban_job_completion_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}))[$__rate_interval]))[48h]) * 60\n+ avg_over_time((rate((sum(oban_job_exception_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}))[$__rate_interval]))[48h]) * 60\n# By default downtime is excluded from average; use below if it should count as zeroes instead (both VictoriaMetrics and Prometheus)\n#avg_over_time((rate((sum(oban_job_completion_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}))[$__rate_interval]) or 0)[48h]) * 60\n#+ avg_over_time((rate((sum(oban_job_exception_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}))[$__rate_interval]) or 0)[48h]) * 60",
     "legendFormat": "Job Total"
    }
   ]
  },
  {
   "title": "Outgoing Requests per Min. - 24h Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(tesla_request_completed_count{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval]))[24h]) * 60",
     "legendFormat": "Outgoing Request Count per Minute"
    }
   ]
  },
  {
   "title": "HTTP Proc Time per Minute - 24h Avg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(phoenix_router_dispatch_stop_duration_sum{job=\"${SCRAPE_JOB}\", instance=\"${INSTANCE}\"}[$__rate_interval]))[24h]) * 60",
     "legendFormat": "HTTP Proc Time per Min"
    }
   ]
  }
 ]
}