depends_on:
- lint

matrix:
  ELIXIR_VERSION:
  - 1.13

pipeline:
  build:
    image: pleromaforkci/ci-base:${ELIXIR_VERSION}
    when:
      event:
      - push
      - pull_request
    environment:
      MIX_ENV: test
    commands:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix compile

  test:
    group: test
    image: pleromaforkci/ci-base:${ELIXIR_VERSION}
    when:
      event:
      - push
      - pull_request
    environment:
      MIX_ENV: test
      POSTGRES_DB: pleroma_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: postgres
    commands:
    - mix local.hex --force
    - mix local.rebar --force
    - mix ecto.drop -f -q
    - mix ecto.create
    - mix ecto.migrate
    - mix test --preload-modules --exclude erratic --exclude federated --max-cases 4
     
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pleroma_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
