labels:
  platform: linux/amd64

depends_on:
  - build-amd64

when:
  event:
    - push
  branch:
    - develop
    - stable

steps:
  docs:
    environment:
      CI: "true"
      SCW_ACCESS_KEY:
        from_secret: SCW_ACCESS_KEY
      SCW_SECRET_KEY:
        from_secret: SCW_SECRET_KEY
      SCW_DEFAULT_ORGANIZATION_ID:
        from_secret: SCW_DEFAULT_ORGANIZATION_ID
    image: python:3.10-slim
    commands:
      - apt-get update && apt-get install -y rclone wget git zip
      - wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64
      - mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli
      - chmod +x scaleway-cli
      - ./scaleway-cli object config install type=rclone
      - cd docs
      - pip install -r requirements.txt
      - mkdocs build
      - zip -r docs.zip site/*
      - cd site
      - rclone copy . scaleway:akkoma-docs/$CI_COMMIT_BRANCH/
